# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginVertDegrade.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#imort necessaire a main
from Custom_Widgets.Widgets import *
import os
import sys
from main import MainWindow
from ui_Principal import *
import threading
import main
    

#import de login
import sqlite3
import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(630, 465)
        
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 20, 590, 420))
        self.widget.setStyleSheet("QPushButton#seConnecter{\n"
"    background-color: rgba(85, 98, 112, 255);\n"
"    color: rgba(255, 255, 255, 200);    \n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#seConnecter:pressed{\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: #8fe31c;\n"
"    background-position: calc(100%  - 10px)center;\n"
"}\n"
"\n"
"QPushButton#seConnecter:hover{\n"
"    background-color: #8fe31c;\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(290, 40, 260, 330))
        self.label.setStyleSheet("background-color: white;\n"
"border-radius: 15px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 25, 270, 360))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8fe31c, stop:1 #008102);\n"
"border-radius: 15px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(380, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(0,0,0,200);")
        self.label_3.setObjectName("label_3")
        self.inputUser = QtWidgets.QLineEdit(self.widget)
        self.inputUser.setGeometry(QtCore.QRect(330, 140, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.inputUser.setFont(font)
        self.inputUser.setStyleSheet("background-color: rgb(0,0 , 0, 0);\n"
"border: 2px solid rgb(0,0 , 0, 0);\n"
"border-bottom-color: rgb(46,82 , 101, 200);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 7px;")
        self.inputUser.setObjectName("inputUser")
        self.inputPswrd = QtWidgets.QLineEdit(self.widget)
        self.inputPswrd.setGeometry(QtCore.QRect(330, 220, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.inputPswrd.setFont(font)
        self.inputPswrd.setStyleSheet("background-color: rgb(0,0 , 0, 0);\n"
"border: 2px solid rgb(0,0 , 0, 0);\n"
"border-bottom-color: rgb(46,82 , 101, 200);\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 7px;")
        self.inputPswrd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.inputPswrd.setObjectName("inputPswrd")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(150, 90, 61, 71))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(120, 200, 121, 121))
        self.label_5.setStyleSheet("color: #8fe31c;")
        self.label_5.setObjectName("label_5")
        self.seConnecter = QtWidgets.QPushButton(self.widget)
        self.seConnecter.setGeometry(QtCore.QRect(330, 300, 191, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.seConnecter.setFont(font)
        self.seConnecter.setObjectName("seConnecter")
        
        self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.label_2.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0))
        self.seConnecter.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3))

        self.seConnecter.clicked.connect(self.Connexion)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    ###################################################################################################
    ###################################################################################################
    def Connexion(self):
        userName = self.inputUser.text()
        password = self.inputPswrd.text()
         # connexion à la base de données
        con = sqlite3.connect('CamShoot.db')
        cur = con.cursor()
        cur.execute("select * from Login")
        
        RqtResult = cur.fetchall()
        
        UserBD = RqtResult[0][1]
        PasswordBD = RqtResult[0][2]
        print(UserBD)
        print(PasswordBD)
        
        # if userName == "":
        #     userName = "Admin"
        
        if ((str(password) == str(PasswordBD)) and (str(UserBD) == str(userName))):
            self.inputUser.setText("")
            self.inputPswrd.setText("")
            
            self.open_main_window()    
            
            ########################################################################
            ## END===>
            ########################################################################
            con.close()
            ###################################################################################################
            ###################################################################################################
    def open_main_window(self):
         # Créez une instance de la fenêtre principale (MainWindow)
        main_window = main.MainWindow()  
    
        # Affichez la fenêtre principale
        main_window.show()
    
        # Fermez la fenêtre de connexion actuelle
        Form.close()  
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Connexion"))
        self.inputUser.setPlaceholderText(_translate("Form", "nom d\'utilisateur"))
        self.inputPswrd.setPlaceholderText(_translate("Form", "mot de passe"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix/logo.png\"/></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><img src=\":/newPrefix2/masque.png\"/></p></body></html>"))
        self.seConnecter.setText(_translate("Form", "Se connecter"))
import logo_rc

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

